import os
import time

import yfinance as yf

from pipeline_config import RAW_STOCKS_DIR, ensure_data_directories

# Lista extensa de tickers de NYSE (600 tickers de ejemplo)
nyse_tickers = [
    "A", "AA", "AAC", "AAN", "AAP", "AAT", "AB", "ABBV", "ABC", "ABEV",
    "ABG", "ABM", "ABR", "ABT", "AC", "ACA", "ACCO", "ACH", "ACM", "ACN",
    "AD", "ADC", "ADM", "ADNT", "ADS", "ADSW", "ADT", "AEE", "AEG", "AEL",
    "AEM", "AEO", "AEP", "AES", "AFG", "AFI", "AFL", "AFSI", "AG", "AGCO",
    "AGD", "AGEN", "AGI", "AGM", "AGN", "AGO", "AGR", "AGRO", "AGX", "AHC",
    "AHL", "AHT", "AI", "AIG", "AIN", "AIR", "AIT", "AIV", "AIZ", "AJG",
    "AJRD", "AKO.A", "AKO.B", "AKR", "AKS", "AL", "ALG", "ALK", "ALL", "ALLE",
    "ALLY", "ALSN", "ALV", "ALX", "AM", "AMBR", "AMC", "AME", "AMG", "AMH",
    "AMK", "AMN", "AMOV", "AMP", "AMRC", "AMRX", "AMT", "AMX", "AN", "ANET",
    "ANF", "ANH", "ANTM", "AON", "AOS", "APA", "APAM", "APD", "APF", "APH",
    "APLE", "APO", "APRN", "APT", "APTS", "APTV", "AQN", "AR", "ARA", "ARCO",
    "ARE", "ARES", "ARI", "ARL", "ARNC", "ARO", "ARR", "ARW", "ASA", "ASB",
    "ASC", "ASGN", "ASH", "ASIX", "ASPN", "ASR", "ASX", "AT", "ATEC", "ATEN",
    "ATGE", "ATH", "ATI", "ATKR", "ATNX", "ATO", "ATR", "ATTO", "ATUS", "AU",
    "AUO", "AUPH", "AVA", "AVAL", "AVB", "AVD", "AVH", "AVK", "AVLR", "AVNS",
    "AVNT", "AVP", "AVT", "AVTR", "AVX", "AVYA", "AWF", "AWI", "AWK", "AWR",
    "AX", "AXE", "AXL", "AXP", "AXR", "AXS", "AXTA", "AY", "AYI", "AYX", "AZN",
    "AZO", "AZRE", "AZUL", "AZZ", "B", "BA", "BABA", "BAC", "BAH", "BAM", "BANC",
    "BAP", "BAS", "BAX", "BB", "BBAR", "BBD", "BBDO", "BBF", "BBK", "BBL", "BBU",
    "BBVA", "BBW", "BBY", "BC", "BCC", "BCE", "BCEI", "BCH", "BCO", "BCOR", "BCS",
    "BCSF", "BDC", "BDJ", "BDN", "BDX", "BE", "BEAT", "BEK.A", "BEKE", "BEN", "BEP",
    "BERY", "BEST", "BF.A", "BF.B", "BFC", "BFS", "BFY", "BFZ", "BG", "BGB", "BGG",
    "BGH", "BGR", "BGS", "BGSF", "BGT", "BGX", "BGY", "BH", "BH.A", "BHC", "BHE",
    "BHK", "BHLB", "BHP", "BHR", "BHV", "BHVN", "BIF", "BIG", "BILL", "BIO", "BIP",
    "BIS", "BIT", "BIV", "BIVI", "BJ", "BK", "BKD", "BKE", "BKH", "BKI", "BKNG",
    "BKR", "BKT", "BKU", "BLD", "BLDR", "BLOK", "BLU", "BLW", "BLX", "BMA", "BME",
    "BMI", "BMLP", "BMO", "BMR", "BMY", "BNED", "BNL", "BNS", "BNY", "BOE", "BOH",
    "BOOT", "BORR", "BOXL", "BP", "BPMP", "BPT", "BPYU", "BQH", "BR", "BRBR", "BRC",
    "BRFS", "BRK.A", "BRK.B", "BRMK", "BRO", "BRS", "BRX", "BSAC", "BSAQ", "BSBR",
    "BSGM", "BSIG", "BSL", "BSM", "BSMX", "BST", "BSTZ", "BSX", "BTA", "BTG", "BTI",
    "BTO", "BTT", "BTU", "BTZ", "BUD", "BUI", "BURL", "BV", "BVN", "BW", "BWA", "BWG",
    "BWL.A", "BWXT", "BX", "BXC", "BXG", "BXMT", "BXMX", "BXP", "BXRX", "BY", "BYD",
    "BYFC", "BYN", "BZH", "BZM", "C", "CAAP", "CABO", "CACI", "CADE", "CAE", "CAF",
    "CAG", "CAH", "CAI", "CAJ", "CAL", "CALA", "CALM", "CALX", "CAN", "CAPL", "CAR",
    "CARG", "CARR", "CARS", "CAS", "CAT", "CATO", "CB", "CBB", "CBD", "CBH", "CBL",
    "CBRE", "CBT", "CBU", "CBZ", "CC", "CCC", "CCEP", "CCI", "CCJ", "CCK", "CCL",
    "CCM", "CCO", "CCS", "CCU", "CCV", "CCX", "CCXI", "CCZ", "CDAY", "CDE", "CDK",
    "CDR", "CE", "CEA", "CEE", "CEIX", "CEL", "CELG", "CELP", "CEM", "CEN", "CEO",
    "CEPU", "CEQP", "CF", "CFG", "CGA", "CHA", "CHCT", "CHD", "CHE", "CHGG", "CHH",
    "CHK", "CHL", "CHMI", "CHMT", "CHN", "CHRA", "CHS", "CHT", "CHU", "CI", "CIA",
    "CIB", "CIEN", "CIF", "CIG", "CII", "CIM", "CINF", "CIO", "CIR", "CIT", "CIX",
    "CL", "CLB", "CLDR", "CLDT", "CLF", "CLGX", "CLH", "CLI", "CLN", "CLNY", "CLR",
    "CLS", "CLW", "CLX", "CMA", "CMC", "CMCM", "CMI", "CMO", "CMP", "CMRE", "CMU",
    "CNA", "CNC", "CNCO", "CNF", "CNI", "CNK", "CNL", "CNM", "CNO", "CNP", "CNQ",
    "CNR", "CNS", "CNV", "CNX", "CO", "CODI", "COF", "COG", "COLD", "COLM", "COM",
    "COMM", "CON", "COO", "COP", "COR", "CORR", "COT", "COTY", "CP", "CPA", "CPAC",
    "CPB", "CPE", "CPF", "CPG", "CPK", "CPL", "CPLG", "CPRI", "CPS", "CPT", "CR",
    "CRC", "CRD.A", "CRD.B", "CRH", "CRI", "CRK", "CRL", "CRM", "CROX", "CRS", "CRT",
    "CRY", "CS", "CSAN", "CSCO", "CSGP", "CSL", "CSLT", "CSQ", "CSR", "CSS", "CSTM",
    "CSU", "CSX", "CTAA", "CTB", "CTDD", "CTE", "CTF", "CTG", "CTK", "CTL", "CTLT",
    "CTO", "CTRA", "CTRE", "CTRL", "CTRN", "CTS", "CTSH", "CTST", "CTT", "CTV", "CTVA",
    "CTW", "CTWS", "CTX", "CTXS", "CUB", "CUBE", "CUBI", "CUK", "CULP", "CUO", "CUR",
    "CUTR", "CUZ", "CVA", "CVE", "CVEO", "CVI", "CVLT", "CVNA", "CVS", "CVX", "CW",
    "CWEN", "CWH", "CWK", "CWT", "CX", "CXO", "CXW", "CYAN", "CYB", "CYCC", "CYD",
    "CYH", "CZR", "D", "DAC", "DAL", "DAN", "DAO", "DAR", "DATA", "DAWN", "DB", "DBD",
    "DBI", "DBO", "DBX", "DCI", "DCO", "DCP", "DD", "DDD", "DDF", "DDS", "DDT", "DE",
    "DEA", "DECK", "DEG", "DEI", "DELL", "DEO", "DESP", "DEX", "DF", "DFIN", "DFNS",
    "DFRG", "DFS", "DG", "DGAZ", "DGICA", "DGICB", "DGX", "DHF", "DHI", "DHR", "DHT",
    "DHX", "DIN", "DIOD", "DIS", "DISH", "DK", "DKL", "DKS", "DL", "DLB", "DLHC", "DLNG",
    "DLPH", "DLR", "DLTH", "DLX", "DM", "DMB", "DMO", "DNB", "DNI", "DNJR", "DNKN", "DNP",
    "DNR", "DO", "DOC", "DOG", "DOGZ", "DOMO", "DOOR", "DORM", "DOV", "DOW", "DPLO", "DPZ",
    "DQ", "DRD", "DRE", "DRH", "DRI", "DRNA", "DRQ", "DRRX", "DS", "DSE", "DSGX", "DSKE",
    "DSL", "DSM", "DSPG", "DSS", "DSTL", "DSU", "DSX", "DT", "DTE", "DTF", "DTJ", "DTL",
    "DTN", "DTP", "DTQ", "DTR", "DTW", "DUK", "DVA", "DVD", "DVN", "DX", "DXC", "DXJ",
    "DXPE", "DXYN", "DY", "DYAI", "DYFN", "DYNC", "DYNT", "DYSL", "DYT", "DYX", "DZK",
    "DZSI", "E", "EA", "EAF", "EAI", "EARN", "EAT", "EBAY", "EBF", "EBIX", "EBS", "EBTC",
    "EC", "ECA", "ECC", "ECL", "ECOL", "ECPG", "ED", "EDD", "EDF", "EDI", "EDN", "EDR",
    "EDU", "EEA", "EEP", "EEX", "EFA", "EFC", "EFF", "EFG", "EFII", "EFL", "EFOI", "EFR",
    "EFT", "EFX", "EGAN", "EGBN", "EGF", "EGHT", "EGN", "EGO", "EGP", "EGY", "EHI", "EHT",
    "EIC", "EIG", "EIGI", "EIX", "EJF", "EJH", "EKSO", "EL", "ELA", "ELAN", "ELC", "ELF",
    "ELLO", "ELS", "ELSE", "ELTK", "ELVT", "ELY", "EMB", "EMCF", "EMCI", "EMD", "EME", "EMF",
    "EMKR", "EML", "EMMS", "EMN", "EMO", "EMR", "ENB", "ENBL", "ENIA", "ENIC", "ENJ", "ENLC",
    "ENLV", "ENLVV", "ENOB", "ENOC", "ENPH", "ENS", "ENSG", "ENT", "ENTA", "ENTG", "ENV",
    "ENVA", "ENZ", "EOCC", "EOD", "EOG", "EPC", "EPD", "EPE", "EPIQ", "EPM", "EPR", "EPRT",
    "EQ", "EQBK", "EQC", "EQH", "EQM", "EQNR", "EQR", "EQS", "EQT", "EQX", "ERA", "ERF", "ERJ",
    "EROS", "ES", "ESBA", "ESBK", "ESCA", "ESE", "ESI", "ESL", "ESLT", "ESNT", "ESP", "ESRT",
    "ESS", "ESV", "ET", "ETB", "ETG", "ETH", "ETJ", "ETM", "ETN", "ETO", "ETP", "ETR", "ETRN",
    "ETV", "ETW", "ETX", "ETY", "EURN", "EV", "EVA", "EVBG", "EVBN", "EVC", "EVER", "EVF", "EVG",
    "EVH", "EVI", "EVN", "EVRI", "EVTC", "EW", "EXD", "EXEL", "EXK", "EXL", "EXP", "EXPR", "EXR",
    "EXTN", "EYE", "EYES", "EZPW", "EZU", "F", "FAB", "FAC", "FAF", "FALN", "FAMI", "FANG", "FARM",
    "FARO", "FAST", "FAT", "FAX", "FB", "FBHS", "FBIO", "FBIZ", "FBK", "FBMS", "FBNC", "FBP", "FBR",
    "FBSS", "FC", "FCAC", "FCAU", "FCB", "FCBC", "FCCY", "FCE.A", "FCE.B", "FCEL", "FCF", "FCFS", "FCN",
    "FCPT", "FCSC", "FCT", "FCX", "FDBC", "FDEF", "FDI", "FDIS", "FDL", "FDMT", "FDP", "FDS", "FDX",
    "FE", "FEAC", "FELE", "FENG", "FET", "FEUZ", "FEX", "FEZ", "FF", "FFA", "FFBC", "FFBW", "FFC",
    "FFG", "FFHL", "FFIC", "FFIN", "FFIV", "FFNW", "FFWM", "FG", "FGB", "FGBI", "FGP", "FHB", "FHI",
    "FHN", "FIBK", "FICO", "FIF", "FIG", "FIGB", "FIGT", "FIGY", "FIHD", "FII", "FILL", "FIM", "FINL",
    "FINS", "FINV", "FIP", "FIS", "FISI", "FISV", "FITB", "FITBI", "FITBO", "FITBP", "FIVN", "FIX", "FIXX",
    "FIZZ", "FL", "FLAU", "FLDM", "FLEX", "FLIR", "FLMN", "FLNG", "FLO", "FLOW", "FLR", "FLS", "FLT", "FLWS",
    "FLXN", "FLXS", "FLY", "FMAG", "FMB", "FMBH", "FMC", "FMCI", "FMCX", "FMI", "FMNB", "FMS", "FMSA", "FMX",
    "FN", "FNA", "FNB", "FNBC", "FNCB", "FND", "FNF", "FNHC", "FNK", "FNLC", "FNV", "FOE", "FOLD", "FOR",
    "FORR", "FORTY", "FOSL", "FOUR", "FPA", "FPAC", "FPAY", "FPF", "FPH", "FPI", "FPL", "FPRX", "FPT", "FPX",
    "FPXE", "FQAL", "FR", "FRA", "FRAF", "FRAN", "FRBA", "FRBK", "FRC", "FRD", "FRED", "FREE", "FREQ", "FREY",
    "FRF", "FRG", "FRGI", "FRHC", "FRI", "FRME", "FRO", "FRPH", "FRPT", "FRSX", "FRT", "FRTA", "FRTG", "FRX",
    "FSB", "FSBC", "FSBW", "FSD", "FSFG", "FSI", "FSK", "FSLY", "FSM", "FSNN", "FSP", "FSR", "FSRV", "FSS",
    "FST", "FSTA", "FSTX", "FSV", "FT", "FTA", "FTAG", "FTAI", "FTC", "FTCS", "FTD", "FTE", "FTEK", "FTFT",
    "FTGC", "FTI", "FTK", "FTNT", "FTR", "FTS", "FTSI", "FTV", "FTXD", "FTXL", "FTXR", "FUL", "FUNC", "FUND",
    "FUNL", "FUSE", "FUV", "FVAL", "FVC", "FVD", "FVE", "FW", "FWAV", "FWONA", "FWONK", "FWP", "FWRD", "FXA",
    "FXB", "FXC", "FXD", "FXE", "FXF", "FXG", "FXH", "FXI", "FXL", "FXN", "FXO", "FXP", "FXR", "FXS", "FXU",
    "FXY", "FXZ", "FYX", "FZT", "G", "GAA", "GAB", "GABC", "GAIA", "GAIN", "GAL", "GALT", "GAM", "GAMR",
    "GAN", "GARS", "GASS", "GATX", "GAZ", "GBCI", "GBDC", "GBF", "GBGR", "GBL", "GBLI", "GBR", "GBRG",
    "GBT", "GBX", "GCAP", "GCBC", "GCE", "GCI", "GCO", "GCV", "GD", "GDDY", "GDEN", "GDF", "GDI", "GDL",
    "GDO", "GDOT", "GDP", "GDS", "GDV", "GDX", "GDXJ", "GDYN", "GE", "GEC", "GECC", "GEF", "GEF.B", "GEG",
    "GEK", "GEL", "GEM", "GEN", "GEO", "GER", "GES", "GEVO", "GF", "GFA", "GFED", "GFIX", "GFL", "GFN",
    "GFNCP", "GFNSZ", "GGB", "GGG", "GGM", "GGN", "GGO", "GGP", "GGT", "GGZ", "GHC", "GHG", "GHI", "GHII",
    "GHL", "GHM", "GHSI", "GHT", "GHY", "GIB", "GIFI", "GIG", "GIGB", "GIFI", "GIII", "GIL", "GILT", "GIM",
    "GIS", "GIX", "GJH", "GJO", "GJS", "GJT", "GKOS", "GL", "GLAD", "GLBS", "GLBZ", "GLDD", "GLDI", "GLG",
    "GLL", "GLMD", "GLNG", "GLO", "GLOB", "GLOG", "GLOP", "GLP", "GLPG", "GLPI", "GLRE", "GLT", "GLU",
    "GLUU", "GLW", "GM", "GME", "GMED", "GMF", "GMOM", "GMS", "GMTA", "GMZ", "GNBC", "GNC", "GNFT",
    "GNK", "GNL", "GNLN", "GNMK", "GNRT", "GNRX", "GNT", "GNTY", "GNUS", "GNW", "GO", "GOAU", "GOF",
    "GOGL", "GOL", "GOLD", "GOOD", "GOOGL", "GORO", "GOSS", "GPA", "GPC", "GPI", "GPJA", "GPK", "GPL",
    "GPM", "GPN", "GPOR", "GPP", "GPRE", "GPRK", "GPRO", "GPS", "GRBK", "GRC", "GREK", "GRES", "GRF",
    "GRFS", "GRMN", "GRMY", "GRN", "GRPN", "GRSH", "GRT", "GRTX", "GRU", "GRUB", "GRVY", "GS", "GSBC",
    "GSBD", "GSH", "GSHT", "GSIH", "GSK", "GSL", "GSS", "GST", "GSUM", "GSV", "GSVC", "GTE", "GTES",
    "GTIM", "GTLS", "GTO", "GTS", "GTT", "GTY", "GTX", "GUNR", "GURE", "GURU", "GUT", "GVA", "GWB",
    "GWGH", "GWR", "GWRS", "GWW", "GWX", "GXC", "GYB", "GYC", "GYO", "GZ", "GZT", "H", "HAE", "HAL", "HASI", "HBAN", "HBI", "HBM", "HCA", "HCC", "HCI",
    "HCN", "HCP", "HCSG", "HD", "HDB", "HE", "HEI", "HEP", "HES", "HESM",
    "HFC", "HFRO", "HGV", "HHC", "HHS", "HI", "HIG", "HII", "HIL", "HIO",
    "HIVE", "HIW", "HIX", "HK", "HL", "HLF", "HLI", "HLT", "HLX", "HMC",
    "HMLP", "HMN", "HMY", "HNGR", "HNI", "HNP", "HNRG", "HOFT", "HOG",
    "HOME", "HON", "HOV", "HP", "HPE", "HPF", "HPI", "HPP", "HPQ", "HPR",
    "HPS", "HQH", "HQL", "HR", "HRB", "HRC", "HRL", "HRS", "HRTG", "HRTX",
    "HSB", "HSBC", "HSC", "HST", "HSY", "HT", "HTA", "HTD", "HTGC", "HTH",
    "HTY", "HTZ", "HUBB", "HUBG", "HUM", "HUN", "HVB", "HVT", "HXL", "HY",
    "HYB", "HYI", "HYT", "HZN", "HZO", "I", "IAG", "IBA", "IBM", "IBN",
    "IBP", "ICD", "ICE", "ICL", "IDA", "IDE", "IDT", "IFF", "IGD", "IGI",
    "IGT", "IHC", "IHG", "IHS", "IHT", "IIF", "IIM", "IIP", "IMAX", "INN",
    "INSI", "INST", "INT", "INVH", "INXN", "IO", "IP", "IPG", "IPHI", "IPI",
    "IQI", "IR", "IRET", "IRL", "IRM", "IRR", "IRS", "IRT", "ISD", "ISF",
    "ISG", "IT", "ITCB", "ITGR", "ITT", "ITUB", "IVC", "IVH", "IVR", "IVZ",
    "IX", "J", "JAX", "JBGS", "JBL", "JBT", "JCI", "JCO", "JDD", "JE", "JEF",
    "JELD", "JEMD", "JEQ", "JFR", "JGH", "JGV", "JHG", "JHI", "JHS", "JHX",
    "JILL", "JKS", "JLL", "JLS", "JMEI", "JMLP", "JMM", "JMP", "JNJ", "JNPR",
    "JP", "JPC", "JPI", "JPM", "JPS", "JPT", "JQC", "JRI", "JRO", "JRS",
    "JSD", "JTA", "JTD", "JW.A", "JW.B", "JWN", "K", "KAI", "KAMN", "KAR",
    "KB", "KBH", "KBR", "KDMN", "KDP", "KEG", "KELYA", "KELYB", "KEM", "KEN",
    "KEP", "KEX", "KEY", "KEYS", "KFS", "KFY", "KIM", "KIN", "KIO", "KKR",
    "KL", "KMB", "KMF", "KMI", "KMPA", "KMT", "KMX", "KN", "KNL", "KNOP",
    "KNX", "KO", "KODK", "KOF", "KOP", "KOS", "KR", "KRA", "KRC", "KREF",
    "KRG", "KRO", "KRP", "KSS", "KSU", "KT", "KTB", "KTF", "KTH", "KTN",
    "KTOS", "KTP", "KW", "KWR", "KYN", "L", "LABL", "LAD", "LADR", "LAIX",
    "LAZ", "LB", "LBAI", "LBF", "LC", "LCI", "LCII", "LDL", "LDOS", "LDP",
    "LEA", "LEAF", "LEE", "LEG", "LEJU", "LEN", "LEO", "LEU", "LFGR", "LGC",
    "LGF.A", "LGF.B", "LGI", "LH", "LHC", "LHO", "LII", "LIN", "LITB", "LL",
    "LLL", "LLY", "LM", "LMHA", "LMHB", "LMT", "LNC", "LND", "LNN", "LOMA",
    "LOW", "LPG", "LPI", "LPL", "LPT", "LQ", "LQDT", "LRCX", "LRN", "LSI",
    "LTC", "LTHM", "LTM", "LUB", "LUV", "LVS", "LW", "LXFR", "LXFT", "LXP",
    "LXU", "LYB", "LYG", "LYV", "LZB", "M", "MA", "MAA", "MAC", "MAIN",
    "MAN", "MANU", "MAS", "MATX", "MAXR", "MAV", "MBI", "MBT", "MC", "MCB",
    "MCC", "MCD", "MCI", "MCK", "MCN", "MCO", "MCR", "MCS", "MCV", "MCX",
    "MDC", "MDP", "MDR", "MDT", "MDU", "MED", "MEG", "MEI", "MELI", "MEN",
    "MER", "MET", "MFA", "MFC", "MFD", "MFG", "MFGP", "MFIN", "MG", "MGA",
    "MGF", "MGM", "MGP", "MGR", "MGU", "MH", "MHD", "MHE", "MHF", "MHK",
    "MHLA", "MHLD", "MHN", "MHO", "MIC", "MIE", "MIN", "MITT", "MIXT", "MIY",
    "MKC", "MKL", "MLI", "MLM", "MLP", "MLR", "MMC", "MMD", "MMI", "MMM",
    "MMP", "MMS", "MMT", "MMU", "MN", "MNE", "MNK", "MNP", "MNR", "MNRL",
    "MO", "MOD", "MODN", "MOH", "MOS", "MOV", "MPA", "MPC", "MPLX", "MPV",
    "MPW", "MPX", "MQY", "MRC", "MRK", "MRO", "MS", "MSA", "MSB", "MSC",
    "MSCI", "MSD", "MSGE", "MSGN", "MSI", "MSM", "MT", "MTB", "MTD", "MTG",
    "MTH", "MTL", "MTN", "MTOR", "MTR", "MTRN", "MTT", "MTW", "MTX", "MTZ",
    "MUFG", "MUI", "MUJ", "MUR", "MUSA", "MUX", "MVC", "MVF", "MVO", "MVT",
    "MWA", "MX", "MXE", "MXF", "MXL", "MYC", "MYD", "MYE", "MYF", "MYI",
    "MYJ", "MYN", "MYOV", "MZA", "N", "NAC", "NAD", "NAN", "NAO", "NAT", "NAV", "NAZ", "NBB", "NBHC",
    "NBR", "NBRV", "NC", "NCA", "NCB", "NCI", "NCLH", "NCR", "NCV", "NCZ",
    "NDMO", "NDP", "NDRO", "NE", "NEA", "NEE", "NEM", "NEP", "NET", "NEU",
    "NEV", "NEW", "NEWR", "NEX", "NFG", "NFJ", "NFLT", "NGG", "NGL", "NGS",
    "NGVC", "NGVT", "NHA", "NHF", "NHI", "NHS", "NI", "NID", "NIE", "NIM",
    "NIQ", "NJR", "NKE", "NKG", "NKX", "NL", "NLS", "NLSN", "NLY", "NM",
    "NMFC", "NMI", "NMM", "NMR", "NMS", "NMT", "NMY", "NMZ", "NNA", "NNI",
    "NNN", "NNY", "NOA", "NOAH", "NOC", "NOK", "NOM", "NOMD", "NOV", "NOW",
    "NP", "NPK", "NPO", "NPTN", "NPV", "NQP", "NR", "NRE", "NRG", "NRGX",
    "NRK", "NRP", "NRT", "NRUC", "NRZ", "NS", "NSA", "NSC", "NSL", "NSP",
    "NSPR", "NSS", "NTC", "NTG", "NTIP", "NTNX", "NTP", "NTR", "NTX", "NTZ",
    "NUE", "NUM", "NUO", "NUV", "NUW", "NVG", "NVGS", "NVO", "NVR", "NVRO",
    "NVS", "NVST", "NVT", "NVTA", "NWE", "NWHM", "NWJ", "NWN", "NWPX", "NWS",
    "NWSA", "NX", "NXC", "NXJ", "NXN", "NXP", "NXQ", "NXR", "NXRT", "NYC",
    "NYCB", "NYT", "NYV", "NZF", "O", "OAK", "OBE", "OC", "OCFT", "OCN",
    "ODC", "OEC", "OFC", "OFG", "OGE", "OGS", "OHI", "OI", "OIA", "OII",
    "OIS", "OKE", "OLN", "OLP", "OMC", "OMF", "OMI", "ONDK", "ONE", "ONTO",
    "OOMA", "OPP", "OPY", "OR", "ORA", "ORAN", "ORC", "ORCL", "ORI", "ORN",
    "OSB", "OSG", "OSK", "OUT", "OXM", "OXY", "PAA", "PAC", "PACD", "PACK",
    "PAG", "PAGS", "PAI", "PAM", "PANW", "PAR", "PARR", "PAYC", "PB", "PBA",
    "PBB", "PBF", "PBFX", "PBH", "PBI", "PBR", "PBT", "PBY", "PCF", "PCG",
    "PCN", "PCQ", "PDI", "PDM", "PDS", "PDT", "PE", "PEB", "PEG", "PEI",
    "PEN", "PEO", "PER", "PFD", "PFE", "PFF", "PFG", "PFGC", "PFH", "PFK",
    "PFL", "PFN", "PFO", "PFS", "PFSI", "PG", "PGP", "PGR", "PGRE", "PGTI",
    "PH", "PHD", "PHG", "PHH", "PHI", "PHK", "PHM", "PHT", "PHX", "PII",
    "PIM", "PINE", "PING", "PINS", "PIPR", "PIR", "PIY", "PJC", "PJH", "PJT",
    "PK", "PKD", "PKE", "PKG", "PKI", "PKO", "PKX", "PL", "PLD", "PLNT",
    "PLOW", "PLT", "PM", "PMF", "PML", "PMM", "PMO", "PMT", "PMX", "PNC",
    "PNF", "PNI", "PNM", "PNR", "PNW", "POL", "POR", "POST", "PPG", "PPL",
    "PPR", "PPT", "PPX", "PQ", "PQG", "PRA", "PRE", "PRGO", "PRH", "PRI",
    "PRLB", "PRO", "PRS", "PRT", "PRU", "PSA", "PSB", "PSF", "PSN", "PSO",
    "PSTG", "PSTL", "PSX", "PSXP", "PTR", "PTY", "PUK", "PVG", "PVH", "PVL",
    "PWR", "PX", "PXD", "PYN", "PYS", "PYT", "PZC", "PZN", "QD", "QEP",
    "QGEN", "QHC", "QSR", "QTM", "QUAD", "QUOT", "QVCD", "R", "RA", "RAAS",
    "RACE", "RAD", "RAMP", "RBA", "RBC", "RBS", "RC", "RCI", "RCL", "RCS",
    "RDC", "RDFN", "RDN", "RDY", "RE", "RELX", "REN", "RENN", "RES", "RESI",
    "REV", "REVG", "REX", "REX.A", "REZI", "RF", "RFI", "RFP", "RGA", "RGC",
    "RGEN", "RGLD", "RGR", "RGS", "RGT", "RH", "RHI", "RHP", "RIG", "RIO",
    "RIV", "RJF", "RKDA", "RL", "RLGY", "RLI", "RLJ", "RM", "RMAX", "RMD",
    "RMED", "RMI", "RMM", "RMP", "RMT", "RNG", "RNGR", "RNP", "RNR", "RNY",
    "ROG", "ROK", "ROL", "ROP", "ROYT", "RPAI", "RPLA", "RPM", "RPT", "RQI",
    "RRC", "RRD", "RRTS", "RS", "RSA", "RSG", "RST", "RTN", "RTW", "RTX",
    "RUBI", "RVI", "RVLV", "RWT", "RXN", "RY", "RYAM", "RYB", "RYCE", "RYI",
    "RYN", "RZA", "RZB", "S", "SA", "SAB", "SACH", "SAFE", "SAH", "SAIC", "SAIL", "SALT", "SAM",
    "SAN", "SAND", "SAP", "SAR", "SAVE", "SB", "SBAC", "SBB", "SBCF", "SBGI",
    "SBH", "SBI", "SBM", "SBRA", "SBS", "SBSI", "SBT", "SBUX", "SC", "SCA",
    "SCC", "SCD", "SCE", "SCEG", "SCEH", "SCEJ", "SCH", "SCHW", "SCI", "SCL",
    "SCM", "SCS", "SCU", "SCVL", "SCX", "SD", "SDHY", "SDLP", "SDPI", "SE",
    "SEAS", "SEE", "SEM", "SEMG", "SENEA", "SENEB", "SERV", "SF", "SFB",
    "SFE", "SFL", "SFT", "SFUN", "SGU", "SGY", "SHAK", "SHG", "SHI", "SHL",
    "SHLX", "SHO", "SHW", "SI", "SID", "SIEB", "SIEN", "SIF", "SIG", "SII",
    "SITC", "SIX", "SJI", "SJM", "SJR", "SJT", "SJW", "SKM", "SKT", "SKX",
    "SKY", "SLB", "SLCA", "SLF", "SLG", "SLQT", "SLRC", "SM", "SMG", "SMHI",
    "SMLP", "SMM", "SMP", "SN", "SNA", "SNAP", "SNDR", "SNH", "SNN", "SNOW",
    "SNP", "SNR", "SNV", "SNX", "SO", "SOI", "SOJA", "SOL", "SON", "SOR",
    "SPAQ", "SPB", "SPCE", "SPE", "SPG", "SPH", "SPI", "SPKE", "SPLP", "SPN",
    "SPOT", "SPR", "SPXC", "SPXX", "SQ", "SQM", "SQNS", "SR", "SRC", "SRE",
    "SRF", "SRG", "SRI", "SRLP", "SRPT", "SRV", "SSB", "SSD", "SSI", "SSL",
    "SSNC", "SSNT", "SSP", "SSRM", "SSTK", "SSY", "ST", "STA", "STAG", "STAR",
    "STAY", "STC", "STE", "STG", "STI", "STL", "STM", "STN", "STNG", "STOR",
    "STT", "STWD", "STX", "STZ", "SU", "SUI", "SUM", "SUN", "SUP", "SUPV",
    "SURF", "SUZ", "SVM", "SVU", "SWCH", "SWI", "SWK", "SWM", "SWN", "SWT",
    "SWX", "SXC", "SXI", "SXT", "SYF", "SYK", "SYN", "SYX", "SYY", "T", "TAC",
    "TAGS", "TAHO", "TAIT", "TAK", "TAL", "TALO", "TAP", "TARO", "TBB", "TBI",
    "TCAP", "TCDA", "TCF", "TCI", "TCO", "TCP", "TCRD", "TCS", "TCX", "TD",
    "TDA", "TDC", "TDE", "TDF", "TDG", "TDI", "TDIV", "TDJ", "TDOC", "TDS",
    "TDW", "TDY", "TEAF", "TEAM", "TECK", "TEF", "TEI", "TEL", "TEN", "TEO",
    "TEP", "TERM", "TERP", "TEVA", "TEX", "TFX", "TG", "TGH", "TGI", "TGNA",
    "TGP", "TGS", "TGT", "THC", "THD", "THG", "THM", "THO", "THQ", "THR",
    "THS", "TIF", "TISI", "TIXT", "TJX", "TK", "TKC", "TKR", "TLYS", "TM",
    "TME", "TMHC", "TMO", "TMP", "TMST", "TMUS", "TNC", "TNET", "TNK", "TNP",
    "TOL", "TOO", "TOPS", "TPB", "TPC", "TPH", "TPHS", "TPRE", "TPVG", "TPX",
    "TPZ", "TR", "TRC", "TREX", "TRGP", "TRI", "TRK", "TRMB", "TRMK", "TRN",
    "TRNE", "TROX", "TRP", "TRQ", "TRTN", "TRTX", "TRU", "TRV", "TRWH", "TRX",
    "TS", "TSLX", "TSM", "TSN", "TSQ", "TSS", "TSU", "TTC", "TTI", "TTM",
    "TTP", "TTS", "TU", "TUFN", "TUP", "TV", "TVC", "TVE", "TWI", "TWLO",
    "TWN", "TWTR", "TX", "TXMD", "TXN", "TXRH", "TXT", "TY", "TYG", "TYL",
    "UA", "UAA", "UAL", "UAN", "UBA", "UBER", "UBS", "UDR", "UE", "UFI",
    "UFS", "UGI", "UGP", "UHS", "UHT", "UI", "UIS", "UL", "UMC", "UMH", "UN",
    "UNF", "UNFI", "UNH", "UNM", "UNP", "UNT", "UNVR", "UPS", "URI", "USA",
    "USAC", "USB", "USDP", "USFD", "USM", "USNA", "USPH", "USX", "UTF", "UTG",
    "UTHR", "UTI", "UTL", "UTX", "UVE", "UVSP", "UVV", "UZA", "UZB", "UZC",
    "V", "VAC", "VAL", "VALE", "VAM", "VBF", "VBIV", "VBLT", "VBTX", "VC",
    "VCIF", "VCRA", "VCV", "VEC", "VEDL", "VEEV", "VEL", "VET", "VFC", "VGI",
    "VGM", "VGR", "VHI", "VICI", "VIPS", "VIST", "VIV", "VJET", "VKQ", "VKTX",
    "VLGEA", "VLO", "VLRS", "VLT", "VLY", "VMC", "VMI", "VMO", "VMW", "VNCE",
    "VNOM", "VNO", "VNTR", "VOC", "VOD", "VOYA", "VPG", "VPV", "VRS", "VRT",
    "VRTV", "VSH", "VSLR", "VST", "VTA", "VTR", "VVI", "VVNT", "VVR", "VVV",
    "VZ", "W", "WAAS", "WAB", "WAL", "WAT", "WBA", "WBK", "WBS", "WBT",
    "WCC", "WCN", "WD", "WDR", "WEA", "WEC", "WEI", "WELL", "WES", "WEX",
    "WEYS", "WF", "WFC", "WGO", "WH", "WHD", "WHG", "WHR", "WIA", "WIFI",
    "WINA", "WING", "WIT", "WIW", "WK", "WLH", "WLK", "WLKP", "WLL", "WM",
    "WMB", "WMC", "WMK", "WMS", "WMT", "WNC", "WOR", "WORK", "WOW", "WPC",
    "WPG", "WPM", "WPP", "WRB", "WRE", "WRI", "WRK", "WSM", "WSO", "WSR",
    "WST", "WTI", "WTM", "WTRG", "WTRH", "WTS", "WTT", "WTTR", "WU", "WUBA",
    "WWE", "WWW", "WY", "X", "XAN", "XEC", "XFLT", "XHR", "XIN", "XL", "XOM",
    "XPO", "XRF", "XRX", "XYF", "XYL", "Y", "YAC", "YANG", "YELP", "YETI",
    "YEXT", "YPF", "YRD", "YUM", "YUMA", "ZBH", "ZEN", "ZF", "ZNH", "ZTO",
    "ZTR", "ZTS", "ZUO", "ZYME", "ZYNE"
]

# Función para descargar datos históricos con reintentos
def download_historical_data(tickers, output_directory):
    for ticker in tickers:
        retries = 3
        success = False
        while retries > 0 and not success:
            try:
                print(f"Descargando datos para {ticker}...")
                # Descargar datos históricos
                stock = yf.Ticker(ticker)
                hist = stock.history(period="max")
                
                # Verificar si los datos contienen filas
                if hist.empty:
                    print(f"No se encontraron datos para {ticker}. Puede que el símbolo esté eliminado o no tenga datos históricos.")
                    break
                
                # Guardar datos en un archivo CSV
                csv_path = os.path.join(output_directory, f"{ticker}.csv")
                hist.to_csv(csv_path)
                
                print(f"Datos históricos de {ticker} descargados y guardados en {csv_path}")
                success = True
            
            except (ConnectionError, Timeout) as e:
                retries -= 1
                print(f"Error de conexión al descargar datos para {ticker}. Reintentando... ({3 - retries}/3)")
                time.sleep(5)  # Esperar un poco antes de reintentar
            
            except Exception as e:
                print(f"Error al descargar datos para {ticker}: {e}")
                break
        
        # Esperar un poco entre las solicitudes para no sobrecargar la API
        time.sleep(1)

def main():
    ensure_data_directories()
    download_historical_data(nyse_tickers, RAW_STOCKS_DIR)


if __name__ == "__main__":
    main()